# Generated by Django 2.2 on 2022-02-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_linkedin'),
    ]

    operations = [
        migrations.CreateModel(
            name='insta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=2000)),
            ],
        ),
        migrations.RenameModel(
            old_name='linkedin',
            new_name='face',
        ),
        migrations.DeleteModel(
            name='Pic',
        ),
    ]
